It is 22:00 central. Taken some hard knocks. Little behind< put do not fret! much leaning has occured. I have successfully launch a demo of the dash application. Further more I have narrowed and confirmed my dataset, https://collegescorecard.ed.gov/data/ . From that dataset I located the excell translater - https://docs.google.com/spreadsheets/d/1Hj-eMrfvrkc3UEb9GlTxO66h6Ik3q8MKoe_7H3-VdYs/edit#gid=

By quickly scanning the translater there multiply questions I can target. Based on instution  and major, I can predict actaul time to complete the program,  percentage of students working and not working 9 years, median income. 

I will use df['column_names'] to select appropoite variables for this seperating targets and  variable columns. Intend to use gradient boosting to make my initial model before class starts.

In [3]:
import pandas as pd

In [11]:

df = pd.read_csv('https://ed-public-download.app.cloud.gov/downloads/Most-Recent-Cohorts-Scorecard-Elements.csv')

df.head()

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,INSTURL,NPCURL,HCM2,PREDDEG,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
0,100654,100200,1002,Alabama A & M University,Normal,AL,www.aamu.edu/,https://galileo.aamu.edu/NetPriceCalculator/np...,0,3,...,0.4048,0.2645,0.0137,0.315,0.3755,0.2958,0.0289,0.4224,0.2635,0.2852
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,0,3,...,0.5448,0.12,0.0728,0.2583,0.5872,0.0817,0.1398,0.2618,0.3977,0.2008
2,100690,2503400,25034,Amridge University,Montgomery,AL,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,0,3,...,0.4647,0.1912,0.0148,0.3284,0.4391,0.2177,0.028,0.3645,0.4486,0.1589
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,www.uah.edu,finaid.uah.edu/,0,3,...,0.5121,0.1593,0.0165,0.323,0.5361,0.1243,0.0245,0.3947,0.3476,0.2331
4,100724,100500,1005,Alabama State University,Montgomery,AL,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,0,3,...,0.4226,0.0754,0.0254,0.5327,0.3133,0.1286,0.021,0.5804,0.1678,0.2308

In [12]:
df.shape

(7115, 190)

In [13]:

#drop columns with more than 50% of data missing

df1 = df.drop(['RELAFFIL', 'SATVR25', 'SATVR75', 'SATMT25', 'SATMT75', 'SATWR25',
               'SATWR75', 'SATVRMID', 'SATMTMID', 'SATWRMID', 'ACTCM25', 'ACTCM75',
               'ACTEN25', 'ACTEN75', 'ACTMT25', 'ACTMT75', 'ACTWR25', 'ACTWR75',
               'ACTCMMID', 'ACTENMID', 'ACTMTMID', 'ACTWRMID', 'SAT_AVG',
               'SAT_AVG_ALL', 'CIPTFBSANNUAL3', 'CIPTFBSANNUAL4', 'CIPTFBSANNUAL5',
               'CIPTFBSANNUAL6', 'MTHCMP1', 'MTHCMP2', 'MTHCMP3', 'MTHCMP4',
               'MTHCMP5', 'MTHCMP6', 'CIPTITLE5', 'CIPTITLE6', 'CIPTFBS1', 'CIPTFBS2',
               'CIPTFBS3', 'CIPTFBS4', 'CIPTFBS5', 'CIPTFBS6', 'CIPTFBSANNUAL1',
               'CIPTFBSANNUAL2', 'CIPCODE1', 'CIPCODE2', 'CIPCODE3', 'CIPCODE4',
               'CIPCODE5', 'CIPCODE6', 'CIPTITLE1', 'CIPTITLE2', 'CIPTITLE3',
               'CIPTITLE4', 'OMAWDP8_PTNFT_POOLED_SUPP', 'OMENRYP8_PTNFT_POOLED_SUPP',
               'OMENRAP8_PTNFT_POOLED_SUPP', 'OMENRUP8_PTNFT_POOLED_SUPP', 'PRGMOFR',
               'OMENRYP_PARTTIME_POOLED_SUPP', 'OMENRAP_PARTTIME_POOLED_SUPP',
               'OMAWDP8_PARTTIME_POOLED_SUPP', 'OMENRUP_PARTTIME_POOLED_SUPP',
               'OMAWDP8_PTFT_POOLED_SUPP', 'OMENRYP8_PTFT_POOLED_SUPP',
               'OMENRAP8_PTFT_POOLED_SUPP', 'OMENRUP8_PTFT_POOLED_SUPP',
               'C150_4_POOLED_SUPP', 'RET_FTL4_POOLED_SUPP', 'NPT42_PRIV', 'NPT43_PRIV',
               'NPT44_PRIV', 'RET_FT4_POOLED_SUPP', 'RET_PTL4_POOLED_SUPP', 'NPT45_PRIV',
               'NPT4_PUB', 'NPT41_PUB', 'NPT42_PUB', 'NPT43_PUB', 'NPT44_PUB',
               'RET_PT4_POOLED_SUPP', 'NPT45_PUB'], axis=1)

#3529
              
df1.isnull().sum().sort_values()

UNITID                                 0
OPEID                                  0
OPEID6                                 0
INSTNM                                 0
CITY                                   0
STABBR                                 0
CURROPER                               0
HCM2                                   0
PREDDEG                                0
HIGHDEG                                0
CONTROL                                0
OPEFLAG                                0
HSI                                    0
INSTURL                               19
GRAD_DEBT_MDN_SUPP                   195
GRAD_DEBT_MDN10YR_SUPP               195
MENONLY                              444
WOMENONLY                            444
DISTANCEONLY                         444
LOCALE                               444
NPCURL                               504
TRIBAL                               528
AANAPII                              528
PBI                                  528
NANTI                                528
HBCU                                 528
ANNHI                                528
UGDS                                 748
UGDS_WHITE                           749
UGDS_BLACK                           749
                                    ...
UG25ABV                              822
RPY_3YR_RT_SUPP                     1048
MD_EARN_WNE_P10                     1225
OMAWDP8_ALL_POOLED_SUPP             3122
OMENRUP_ALL_POOLED_SUPP             3122
OMENRAP_ALL_POOLED_SUPP             3122
OMENRYP_ALL_POOLED_SUPP             3122
NPT4_PRIV                           3126
OMENRUP_FULLTIME_POOLED_SUPP        3143
OMENRAP_FULLTIME_POOLED_SUPP        3143
OMENRYP_FULLTIME_POOLED_SUPP        3143
OMAWDP8_FULLTIME_POOLED_SUPP        3143
NPT41_PRIV                          3199
OMENRUP_NOTFIRSTTIME_POOLED_SUPP    3219
OMAWDP8_NOTFIRSTTIME_POOLED_SUPP    3219
OMENRAP_NOTFIRSTTIME_POOLED_SUPP    3219
OMENRYP_NOTFIRSTTIME_POOLED_SUPP    3219
OMENRUP_FIRSTTIME_POOLED_SUPP       3229
OMAWDP8_FIRSTTIME_POOLED_SUPP       3229
OMENRYP_FIRSTTIME_POOLED_SUPP       3229
OMENRAP_FIRSTTIME_POOLED_SUPP       3229
OMENRUP8_FTNFT_POOLED_SUPP          3245
OMENRAP8_FTNFT_POOLED_SUPP          3245
OMENRYP8_FTNFT_POOLED_SUPP          3245
OMAWDP8_FTNFT_POOLED_SUPP           3245
OMENRAP8_FTFT_POOLED_SUPP           3259
OMAWDP8_FTFT_POOLED_SUPP            3259
OMENRYP8_FTFT_POOLED_SUPP           3259
OMENRUP8_FTFT_POOLED_SUPP           3259
C150_L4_POOLED_SUPP                 3537
Length: 108, dtype: int64

In [18]:
columns = df1.columns.tolist()

In [19]:
print(columns)

['UNITID', 'OPEID', 'OPEID6', 'INSTNM', 'CITY', 'STABBR', 'INSTURL', 'NPCURL', 'HCM2', 'PREDDEG', 'HIGHDEG', 'CONTROL', 'LOCALE', 'HBCU', 'PBI', 'ANNHI', 'TRIBAL', 'AANAPII', 'HSI', 'NANTI', 'MENONLY', 'WOMENONLY', 'PCIP01', 'PCIP03', 'PCIP04', 'PCIP05', 'PCIP09', 'PCIP10', 'PCIP11', 'PCIP12', 'PCIP13', 'PCIP14', 'PCIP15', 'PCIP16', 'PCIP19', 'PCIP22', 'PCIP23', 'PCIP24', 'PCIP25', 'PCIP26', 'PCIP27', 'PCIP29', 'PCIP30', 'PCIP31', 'PCIP38', 'PCIP39', 'PCIP40', 'PCIP41', 'PCIP42', 'PCIP43', 'PCIP44', 'PCIP45', 'PCIP46', 'PCIP47', 'PCIP48', 'PCIP49', 'PCIP50', 'PCIP51', 'PCIP52', 'PCIP54', 'DISTANCEONLY', 'UGDS', 'UGDS_WHITE', 'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI', 'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN', 'PPTUG_EF', 'CURROPER', 'NPT4_PRIV', 'NPT41_PRIV', 'PCTPELL', 'PCTFLOAN', 'UG25ABV', 'MD_EARN_WNE_P10', 'GRAD_DEBT_MDN_SUPP', 'GRAD_DEBT_MDN10YR_SUPP', 'RPY_3YR_RT_SUPP', 'C150_L4_POOLED_SUPP', 'OMAWDP8_FTFT_POOLED_SUPP', 'OMENRYP8_FTFT_POOLED_SUPP', 'OMENRAP8_FTFT_POOLED_SUPP', 'OMENRUP8_FTFT_POOLED_SUPP', 'OMAWDP8_FTNFT_POOLED_SUPP', 'OMENRYP8_FTNFT_POOLED_SUPP', 'OMENRAP8_FTNFT_POOLED_SUPP', 'OMENRUP8_FTNFT_POOLED_SUPP', 'OPEFLAG', 'OMENRYP_ALL_POOLED_SUPP', 'OMENRAP_ALL_POOLED_SUPP', 'OMAWDP8_ALL_POOLED_SUPP', 'OMENRUP_ALL_POOLED_SUPP', 'OMENRYP_FIRSTTIME_POOLED_SUPP', 'OMENRAP_FIRSTTIME_POOLED_SUPP', 'OMAWDP8_FIRSTTIME_POOLED_SUPP', 'OMENRUP_FIRSTTIME_POOLED_SUPP', 'OMENRYP_NOTFIRSTTIME_POOLED_SUPP', 'OMENRAP_NOTFIRSTTIME_POOLED_SUPP', 'OMAWDP8_NOTFIRSTTIME_POOLED_SUPP', 'OMENRUP_NOTFIRSTTIME_POOLED_SUPP', 'OMENRYP_FULLTIME_POOLED_SUPP', 'OMENRAP_FULLTIME_POOLED_SUPP', 'OMAWDP8_FULLTIME_POOLED_SUPP', 'OMENRUP_FULLTIME_POOLED_SUPP']

At this point I can officially say im be

In [17]:
df1.columns = ['school', 'city', 'monitoring', 'undergrad', 'highest_degree', 'type',
              'locale', 'historically_black', 'primarily_black', 'AN/NH', 'tribal',
              'AA/NA/PI', 'hispanic-serving', 'non-tribal_NA', 'men', 'women',
              'white', 'black', 'hispanic', 'asian', 'AI/AN', 'NH/PI', 'two+',
              'non-res_alien', 'unknown_race', 'priv_price', 'priv_price_income',
              'pct_pell', 'pct_federal', 'undergrads_25+', 'median_earnings_10',
              'med_debt', 'pct_8yr_grad', 'pct_8yr_nongrad']
df1.head()

ValueError: Length mismatch: Expected axis has 108 elements, new values have 34 elements

In [14]:

import matplotlib.pyplot as plt

x = college['median_earnings_10']
y = college['med_debt']

plt.scatter(x, y, color='blue', marker='+')
plt.xlabel('Median Earnings 10 Years After Enrollment')
plt.ylabel('Median Debt')
plt.title('Debt vs. Earnings')
plt.show();

NameError: name 'college' is not defined